# app端口号
server:
  port: 8001
  servlet:
    context-path: /xiaoFF   
  
# 数据源配置
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:MYDB01
    username: myuser
    password: myuser1234
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

# mybatis相关配置
mybatis: 
  #mybatis配置文件位置
  config-location: classpath:/mybatis_config.xml
  #mapper文件所在位置
  mapper-locations: classpath*:/mybatis_mapper/*_mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.example.demo.dto  
 
# pagehelper分页插件相关配置
#pagehelper:
#  helper-dialect: oracleW
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
  
# 日志相关配置
logging:
  config: classpath:logging_config.xml
  
# 该属性置为true的时候，核心Logger（包含嵌入式容器、hibernate、spring）会输出更多内容，但是你自己应用的日志并不会输出为DEBUG级别
debug: true
    
